# Base OS and configuration
FROM {os_type}:{os_version}

# Install dependencies
RUN {install_cmd}

# Install OpenVSCode Server
RUN curl -fsSL https://github.com/gitpod-io/openvscode-server/releases/download/openvscode-server-v{openvscode_version}/openvscode-server-v{openvscode_version}-linux-{openvscode_arch}.tar.gz \
    | tar -xz -C /opt \
    && mv /opt/openvscode-server* /opt/openvscode-server

# Set Hostname
RUN echo {hostname} > /etc/hostname

# Create non-root user
ARG USERNAME={username}
ARG USER_UID={user_uid}
ARG USER_GID={user_uid}
RUN if ! getent group $USER_GID >/dev/null; then \
        groupadd -g $USER_GID $USERNAME; \
    fi \
 && if ! id -u $USER_UID >/dev/null 2>&1; then \
        useradd -m -u $USER_UID -g $USER_GID -s /bin/bash $USERNAME; \
    else \
        echo "User with UID $USER_UID already exists, reusing..."; \
    fi \
 && mkdir -p /home/$USERNAME/.openvscode-server/extensions \
 && chown -R $USER_UID:$USER_GID /home/$USERNAME

USER $USERNAME
WORKDIR /home/$USERNAME

# Expose port
EXPOSE {port}

# Default command
CMD ["/opt/openvscode-server/bin/openvscode-server", "--host", "0.0.0.0", "--port", "{port}", "--without-connection-token"]
